### PR TITLE
For #81: Bump parent

### PR DESCRIPTION
**Pull request by andreoss**
This is for #81:
- Bump parent
- Add puzzle
- Compliance to newer Qulice

### CODE REVIEW

**Comment by andreoss** [comment]
@rultor merge

**Comment by andreoss** [comment]
@rultor merge

**Comment by andreoss** [comment]
Blocked by https://github.com/jcabi/jcabi/pull/324

**Comment by andreoss** [comment]
@rultor merge

**Comment by andreoss** [comment]
@rultor merge

**Comment by andreoss** [comment]
@rultor merge

**Comment by andreoss** [comment]
@rultor release 0.17.4

**Comment by andreoss** [comment]
@rultor release, tag=`0.17.4`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#82` is not assigned, can't get performer

**Pull request merged**
