### PR TITLE
#13 - build hangs on pgsql test

### PR DESCRIPTION
**Pull request by maurezen**
Added a timeout so the build doesn't hang and a postgres log file location for better diagnostic in future.

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@krzyk please review this PR

**Comment by krzyk** [comment]
@maurezen as I understand your fix will make the build fail instead of hang, so let's document that in the README.md file, when developer might expect the build to fail (e.g. admin user under Win7, right?)

**Comment by maurezen** [comment]
@krzyk agreed, done (actually postgres can't be launched under admin/root, ever, so the issue is wider than Win7).

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by krzyk** [comment]
@yegor256 network issue, please try again

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@krzyk I added **15 mins** to your account, many thanks for working with the project!; +15 added to your rating, at the moment it is: [+3649](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
