### PR TITLE
Updated copyright information

### PR DESCRIPTION
**Pull request by aoxa**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@longtimeago it's yours, please review

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@longtimeago Thank you, I've added **15 mins** to your account in payment/transaction "`50614512`"... added +15 to your rating, now it is equal to [+1337](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
