### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Let me find a reviewer for this pull request, thanks for submitting it

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 thanks, I just added **18 mins** to your account, payment `000-7474a4a6`, 9000 hours and 18 mins spent... extra minutes for review comments (c=3)... +18 added to your rating, at the moment it is: [+183](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
