### PR TITLE
#23 fixed documentation in section Maintaining SQL Transactions Through JDBC

### PR DESCRIPTION
**Pull request by darkled**

### CODE REVIEW

**Comment by darkled** [comment]
@longtimeago #33 seems to be closed now, could you please check again?

**Comment by longtimeago** [comment]
@rultor please, merge

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@longtimeago **22 mins** was added to your account, many thanks for your contribution!; +22 to your rating, your total score is [+1199](http://www.netbout.com/b/35024?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy pls

**Pull request merged**
