### PR TITLE
Adding support for float.

### PR DESCRIPTION
**Pull request by piotrkot**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this pull request is too small, just 7 lines changed (less than 10), there will be no formal code review; in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by piotrkot** [comment]
@yegor256 Would that be OK to suppress PMD warning about Cyclomatic Complexity in `PrepareArgs.prepare` method?

**Comment by yegor256** [comment]
@piotrkot yes, it's OK

**Comment by yegor256** [comment]
@rultor merge

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
