### PR TITLE
Setting Object in Prepared statement

### PR DESCRIPTION
**Pull request by piotrkot**
PR for issue no. [68](https://github.com/jcabi/jcabi-jdbc/issues/68)

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by piotrkot** [comment]
@yegor256 Can you please have a look at it? It's just one line.

**Comment by piotrkot** [comment]
@yegor256 Sorry for bugging you, but this issue is somehow blocking me. Is there anything I can do to help you have a look at it?

**Comment by piotrkot** [comment]
@yegor256 ping

**Comment by piotrkot** [comment]
@yegor256 yet another ping

**Comment by yegor256** [comment]
@rultor merge

**Comment by piotrkot** [comment]
@yegor256 Can you make a release, please?

**Comment by longtimeago** [comment]
@yegor256 could we cut a new release with this fix, please?

**Comment by piotrkot** [comment]
@longtimeago `0.17.2` is just released

**Comment by longtimeago** [comment]
@piotrkot thanks a lot! :)

**Pull request merged**
