### PR TITLE
Update psql-driver in order to fix integration tests

### PR DESCRIPTION
**Pull request by andreoss**
- Update postgres jdbc driver to get UUID support.

### CODE REVIEW

**Comment by 0crat** [comment]
@andreoss[/z](https://www.0crat.com/u/andreoss) this pull request is too small, just 5 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by andreoss** [comment]
@rultor merge

**Comment by baudoliver7** [comment]
@yegor256 Could you please check / merge what @andreoss did ? That's ok for me :) There was a need to upgrade postgresql driver to make IT tests succeed with Docker.

**Review by baudoliver7 — APPROVED** [review]
@andreoss Good :)

**Comment by andreoss** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#104` is not assigned, can't get performer

**Pull request merged**
