### PR TITLE
#65 Setting parameter to SQL NULL instead of String

### PR DESCRIPTION
**Pull request by piotrkot**
Using setNull on PreparedStatement

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by piotrkot** [comment]
@yegor256 ping

**Comment by piotrkot** [comment]
@yegor256 Is there anything I can do to help you with this pull request?

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.1`

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-jdbc#66` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by piotrkot** [comment]
@yegor256 Thank you very much!

**Pull request merged**
