### PR TITLE
Have added support for byte[] to be inserted into blob-like fields.

### PR DESCRIPTION
**Pull request by mj1618**
I experienced issues while trying to save images in a BLOB, adding this fixed the problem as it doesn't convert the binary data into another format.

### CODE REVIEW

**Comment by yegor256** [comment]
@rultor try to merge it please

**Comment by yegor256** [comment]
@mj1618 as you see, there are some code formatting issues in your branch. please fix them and we'll try to merge again. thanks for your contribution! :)

**Comment by mj1618** [comment]
No problem, happy to help out.

I think I've cleaned up those 6 issues with the formatting. I have amended the commit, would you like to submit another pull request?

**Comment by yegor256** [comment]
@rultor try to merge again

**Comment by mj1618** [comment]
Great, thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.15`

**Comment by yegor256** [comment]
@mj1618 version 0.15 is in Maven Central. again, thanks for your contribution :)

**Comment by mj1618** [comment]
Hi Yegor,

Keen to contribute a bit more to this project as I'm using jcabi-jdbc quite a bit at the moment.
Do you have somewhere to post and discuss feature suggestions?
As I'm not sure the direction you want to take the project so just want to bounce some ideas off you to see if it's worth putting them into jcabi-jdbc.

**Comment by yegor256** [comment]
@mj1618 just submit them one by one as issues here. We'll discuss them. But make sure you submit one idea at a time, in its own ticket/issue. thanks for using our lib :)

**Pull request merged**
